# Generated by Django 4.2.25 on 2025-10-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_units",
            field=models.CharField(
                choices=[
                    ("metric", "Metric (kg, cm)"),
                    ("imperial", "Imperial (lbs, inches)"),
                ],
                default="imperial",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
    ]
