# Generated by Django 4.2.25 on 2025-10-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_gender_user_preferred_units_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("undisclosed", "Prefer not to say"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_units",
            field=models.CharField(
                choices=[
                    ("metric", "Metric (kg, m)"),
                    ("imperial", "Imperial (lb, ft)"),
                ],
                default="imperial",
                max_length=10,
            ),
        ),
    ]
